### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by yzernik** [dakhodl/peacemaker#15]
I'm trying to follow the instructions in the README, but I get an error on docker-compose up.

```
yzernik@yzernik-MacBookPro:~/work/peacemaker$ docker-compose up
Creating network "peacemaker_development" with the default driver
Creating network "peacemaker_test" with the default driver
Creating peacemaker_postgres_1 ... done
Creating peacemaker_redis_1    ... done
Creating web                   ... done
Creating peacemaker_tor        ... done
Creating peacemaker_worker     ... done
Attaching to peacemaker_postgres_1, peacemaker_redis_1, web, peacemaker_tor, peacemaker_worker
redis_1     | 1:C 08 Apr 01:41:41.118 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 08 Apr 01:41:41.118 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 08 Apr 01:41:41.118 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  | 
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  | 
postgres_1  | Data page checksums are disabled.
redis_1     | 1:M 08 Apr 01:41:41.119 * Running mode=standalone, port=6379.
redis_1     | 1:M 08 Apr 01:41:41.119 # Server initialized
redis_1     | 1:M 08 Apr 01:41:41.119 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 08 Apr 01:41:41.119 * Ready to accept connections
postgres_1  | 
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
tor_1       | cat: can't open '/var/app/hidden_service/hostname': No such file or directory
postgres_1  | selecting default time zone ... UTC
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | performing post-bootstrap initialization ... sh: locale: not found
peacemaker_tor exited with code 1
web         | Environment: development
web         | [TOR] WARNING: hs_ed25519_secret_key, hs_ed25519_public_key, and/or hostname were not specified
web         | [TOR] WARNING: Attempting to generate a new hs_ed25519_secret_key, hs_ed25519_public_key, and hostname
web         | Apr 08 01:41:41.984 [notice] Tor 0.4.6.9 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.12, Liblzma 5.2.5, Libzstd 1.5.0 and Unknown N/A as libc.
web         | Apr 08 01:41:41.984 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
web         | Apr 08 01:41:41.984 [notice] Read configuration file "/var/app/config/torrc-dev".
web         | Apr 08 01:41:41.986 [warn] Path for HiddenServiceDir (hidden_service) is relative and will resolve to /var/app/hidden_service. Is this what you wanted?
web         | Apr 08 01:41:41.988 [warn] You specified a public address '0.0.0.0:9050' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
web         | Apr 08 01:41:41.988 [notice] Opening Socks listener on 0.0.0.0:9050
web         | Apr 08 01:41:41.988 [notice] Opened Socks listener connection (ready) on 0.0.0.0:9050
web         | Apr 08 01:41:41.988 [warn] Error creating directory /var/app/hidden_service/tor-data: No such file or directory
web         | Apr 08 01:41:41.988 [notice] Closing partially-constructed Socks listener connection (ready) on 0.0.0.0:9050
web         | Apr 08 01:41:41.988 [warn] Failed to parse/validate config: Couldn't create private data directory "/var/app/hidden_service/tor-data"
web         | Apr 08 01:41:41.988 [err] Reading config failed--see warnings above.
postgres_1  | 2022-04-08 01:41:41.399 UTC [30] WARNING:  no usable system locales were found
postgres_1  | ok
postgres_1  | syncing data to disk ... ok
postgres_1  | 
postgres_1  | 
postgres_1  | Success. You can now start the database server using:
postgres_1  | 
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  | 
postgres_1  | initdb: warning: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | waiting for server to start....2022-04-08 01:41:42.709 UTC [36] LOG:  starting PostgreSQL 13.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
postgres_1  | 2022-04-08 01:41:42.719 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2022-04-08 01:41:42.746 UTC [37] LOG:  database system was shut down at 2022-04-08 01:41:41 UTC
postgres_1  | 2022-04-08 01:41:42.757 UTC [36] LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
postgres_1  | 
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  | 
postgres_1  | waiting for server to shut down....2022-04-08 01:41:42.791 UTC [36] LOG:  received fast shutdown request
postgres_1  | 2022-04-08 01:41:42.801 UTC [36] LOG:  aborting any active transactions
postgres_1  | 2022-04-08 01:41:42.801 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
postgres_1  | 2022-04-08 01:41:42.801 UTC [38] LOG:  shutting down
postgres_1  | 2022-04-08 01:41:42.879 UTC [36] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  | 
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | 2022-04-08 01:41:42.929 UTC [1] LOG:  starting PostgreSQL 13.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
postgres_1  | 2022-04-08 01:41:42.929 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2022-04-08 01:41:42.929 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2022-04-08 01:41:42.956 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2022-04-08 01:41:42.990 UTC [48] LOG:  database system was shut down at 2022-04-08 01:41:42 UTC
postgres_1  | 2022-04-08 01:41:43.009 UTC [1] LOG:  database system is ready to accept connections
worker_1    | `/` is not writable.
worker_1    | Bundler will use `/tmp/bundler20220408-1-1fgwoeq1' as your home directory temporarily.
worker_1    | `/` is not writable.
worker_1    | Bundler will use `/tmp/bundler20220408-1-13n43dd1' as your home directory temporarily.
worker_1    | Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.2.33). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.33`.
worker_1    | The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
web         | [TOR] FAILURE: Unable to generate a hs_ed25519_secret_key, hs_ed25519_public_key, and hostname
web exited with code 1
worker_1    | Rails Error: Unable to access log file. Please ensure that /var/app/log/development.log exists and is writable (i.e. make it writable for user and group: chmod 0664 /var/app/log/development.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
worker_1    | 2022-04-08T01:41:46.968Z pid=1 tid=4w5 WARN: Errno::ENOENT: No such file or directory @ rb_sysopen - hidden_service/peacemaker_key
worker_1    | 2022-04-08T01:41:46.969Z pid=1 tid=4w5 WARN: /var/app/config/configatron/defaults.rb:20:in `initialize'
worker_1    | /var/app/config/configatron/defaults.rb:20:in `open'
worker_1    | /var/app/config/configatron/defaults.rb:20:in `<top (required)>'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/configatron-4.5.1/lib/configatron/integrations/rails.rb:47:in `require'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/configatron-4.5.1/lib/configatron/integrations/rails.rb:47:in `block in init'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/configatron-4.5.1/lib/configatron/integrations/rails.rb:44:in `each'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/configatron-4.5.1/lib/configatron/integrations/rails.rb:44:in `init'
worker_1    | /var/app/config/initializers/configatron.rb:2:in `<top (required)>'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/engine.rb:667:in `load'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/engine.rb:667:in `block in load_config_initializer'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/notifications.rb:208:in `instrument'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/engine.rb:666:in `load_config_initializer'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/engine.rb:619:in `each'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/engine.rb:619:in `block in <class:Engine>'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/initializable.rb:32:in `instance_exec'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/initializable.rb:32:in `run'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/initializable.rb:50:in `each'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/initializable.rb:50:in `tsort_each_child'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:415:in `call'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
worker_1    | /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/initializable.rb:60:in `run_initializers'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/railties-7.0.0/lib/rails/application.rb:369:in `initialize!'
worker_1    | /var/app/config/environment.rb:5:in `<top (required)>'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/cli.rb:273:in `boot_application'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/cli.rb:37:in `run'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/gems/sidekiq-6.3.1/bin/sidekiq:31:in `<top (required)>'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/bin/sidekiq:23:in `load'
worker_1    | /usr/local/bundle/gems/ruby/2.7.0/bin/sidekiq:23:in `<top (required)>'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
worker_1    | /usr/local/bundle/bin/bundle:23:in `load'
worker_1    | /usr/local/bundle/bin/bundle:23:in `<top (required)>'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
worker_1    | /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
worker_1    | /usr/local/bundle/bin/bundle:23:in `load'
worker_1    | /usr/local/bundle/bin/bundle:23:in `<main>'
peacemaker_worker exited with code 1
```

**Comment by dakhodl** [comment]
Hey welcome to the project thanks for giving it a try.

That's failing on [this line](https://github.com/dakhodl/peacemaker/blob/master/config/configatron/defaults.rb#L20) where it tries to read your pub key that is used to sign requests, [described here in the whitepaper](http://peacemaker.market/whitepaper/#request-signing). The lines above it are _supposed_ to auto-generate that key for you if it doesn't exist. Can you `ls hidden_service` and see if the file `peacemaker_key` is in fact in there on your filesystem? 

I'm trying to understand if the prior `File.exists?` failed or if something is amiss with the way the development environment mounts the whole folder into the container.
